version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: filesize
    versions:
    - 6.1.0
    - 6.2.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
    - 26.0.20
    - 26.0.22
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
    - 10.7.1
  - dependency-name: ts-loader
    versions:
    - 8.0.13
    - 8.0.16
    - 8.0.17
    - 8.1.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.2
    - 1.3.5
    - 1.3.8
  - dependency-name: less-loader
    versions:
    - 7.2.1
